services:
  # Serviço de Frontend com Hot Reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Impede que o node_modules local sobrescreva o do container
    command: npm run dev -- --host

  # API Gateway (Nginx)
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - servico-autenticacao
      - servico-mensagens

  # Serviço de Autenticação com Reload
  servico-autenticacao:
    build: ./backend/servico-autenticacao
    volumes:
      - ./backend/servico-autenticacao:/app
    environment:
      - IS_LOCAL=true # Informa ao Python para usar o banco local
    depends_on:
      - dynamodb-local # Depende do banco local

  # Serviço de Mensagens com Reload
  servico-mensagens:
    build: ./backend/servico-mensagens
    volumes:
      - ./backend/servico-mensagens:/app
    environment:
      - IS_LOCAL=true # Informa ao Python para usar o banco local
    depends_on:
      - dynamodb-local # Depende do banco local

  # DynamoDB Local (Modo Em Memória)
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000" # Porta padrão do DynamoDB Local
    # ALTERADO: Usa -inMemory em vez de -dbPath e remove o volume
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    # volumes: # Linha removida - não salva dados em disco neste modo
    #   - dynamodb-data:/data # Linha removida

# volumes: # Seção removida ou comentada pois não há mais volumes persistentes aqui
#   dynamodb-data: # Linha removida