services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.dev.conf:/etc/nginx/nginx.conf

  servico-autenticacao:
    build: ./backend/servico-autenticacao
    volumes:
      - ./backend/servico-autenticacao:/app
    environment:
      - IS_LOCAL=true

  servico-mensagens:
    build: ./backend/servico-mensagens
    volumes:
      - ./backend/servico-mensagens:/app
    environment:
      - IS_LOCAL=true

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"