services:
  # Serviço de Frontend com Hot Reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  # API Gateway (Nginx)
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - servico-autenticacao
      - servico-mensagens

  # Serviço de Autenticação com Reload
  servico-autenticacao:
    build: ./backend/servico-autenticacao
    volumes:
      - ./backend/servico-autenticacao:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  # Serviço de Mensagens com Reload
  servico-mensagens:
    build: ./backend/servico-mensagens
    volumes:
      - ./backend/servico-mensagens:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  # Novo: Serviço do Banco de Dados MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Mapeamos a porta para podermos inspecionar o DB localmente
    volumes:
      - mongo-data:/data/db

# Novo: Define o volume para persistência dos dados do MongoDB
volumes:
  mongo-data: